### ISSUE TITLE
Missing Meta Files!

### ISSUE THREAD

**Issue by IsaiahKelly** [jmickle66666666/DoomUnity#69]
I started to suspect that the issues I was seeing with missing script references on the player prefab had something to do with the exclusion of meta files, and it turns out my suspicion was correct!

To test this I created a GameObject, attached a few dummy scripts to it, and then saved it as a prefab.

![prefab_with_meta](https://user-images.githubusercontent.com/7953130/40001330-ff92dcf8-575b-11e8-9d79-1f9acbc2000f.png)

Then I deleted all meta files and copied this prefab and it's scripts into a new Unity project and this was the result.

![prefab_without_meta](https://user-images.githubusercontent.com/7953130/40001419-28d6a356-575c-11e8-8ac1-b34e12e2f9be.png)
Both scripts attached to the prefab are still included in the folder and have not been renamed, but apparently Unity depends on the meta files to know what is attached to the prefab.

**So you should NOT exclude meta files if you want prefabs (and probably other files) to work properly in Unity!** 

I was going to make a commit to change this myself, but it's probably best if you do that yourself so the original meta files from your own project get added, instead of my own, which will have completely different IDs and might cause conflicts with yours.

**Comment by jmickle66666666** [comment]
Ah! I didn't know this, thanks for the research! 

I wasn't super sure how I should host this project on github, since it was originally meant to just be a code library for working with Doom. Now it has become an engine too I will probably restructure the repo to host the entire project. I'll get those meta files added!

**Comment by jmickle66666666** [comment]
Should be fixed in 745d65a5d35ce91c56af9325f41471f4fd4c3ba5
